magic_list = ('fire magic', 'air magic', 'water magic', 'earth magic')

skill_list = ['pathfinding', 'archery', 'logistics', 'scouting', 'diplomacy', 'navigation', 'leadership', 'wisdom', 'mysticism', 'luck', 'ballistics', 'eagle eye', 'necromancy', 'estates', 'fire magic', 'air magic', 'water magic', 'earth magic', 'scholar', 'tactics', 'artillery', 'learning',
              'offense', 'armorer', 'intelligence', 'sorcery', 'resistance', 'first aid', 'interference']
hero_classes_pri = {
    'knight': ((35, 45, 10, 10), (30, 30, 20, 20)),
    'cleric': ((20, 15, 30, 35), (20, 20, 30, 30)),
    'ranger': ((35, 45, 10, 10), (30, 30, 20, 20)),
    'druid': ((10, 20, 35, 35), (20, 20, 30, 30)),
    'alchemist': ((30, 30, 20, 20), (30, 30, 20, 20)),
    'wizard': ((10, 10, 40, 40), (30, 20, 20, 30)),
    'demoniac': ((35, 35, 15, 15), (30, 30, 20, 20)),
    'heretic': ((15, 15, 35, 35), (20, 20, 30, 30)),
    'death knight': ((30, 25, 20, 25), (25, 25, 25, 25)),
    'necromancer': ((15, 15, 35, 35), (25, 25, 25, 25)),
    'overlord': ((35, 35, 15, 15), (30, 30, 20, 20)),
    'warlock': ((10, 10, 50, 30), (20, 20, 30, 30)),
    'barbarian': ((55, 35, 5, 5), (30, 30, 20, 20)),
    'battle mage': ((30, 20, 25, 25), (25, 25, 25, 25)),
    'beastmaster': ((30, 50, 10, 10), (30, 30, 20, 20)),
    'witch': ((5, 15, 40, 40), (20, 20, 30, 30)),
    'planeswalker': ((45, 25, 15, 15), (30, 30, 20, 20)),
    'elementalist': ((15, 15, 35, 35), (25, 25, 25, 25)),
    'captain': ((45, 25, 20, 10), (30, 30, 20, 20)),
    'navigator': ((15, 10, 40, 35), (30, 20, 20, 30))
}

hero_classes_sec = {
    'knight': {'artillery': 5, 'ballistics': 8, 'sorcery': 1, 'scholar': 1, 'diplomacy': 4, 'armorer': 5, 'eagle eye': 2, 'estates': 6, 'intelligence': 1, 'leadership': 10, 'logistics': 5, 'water magic': 4, 'air magic': 3, 'earth magic': 2, 'fire magic': 1, 'mysticism': 2, 'wisdom': 3, 'navigation': 8, 'offense': 7, 'learning': 4, 'first aid': 2, 'pathfinding': 4, 'interference': 5, 'scouting': 4, 'resistance': 5, 'archery': 5, 'tactics': 7, 'luck': 3, 'necromancy': 0},
    'cleric': {'artillery': 2, 'ballistics': 4, 'sorcery': 5, 'scholar': 6, 'diplomacy': 7, 'armorer': 3, 'eagle eye': 6, 'estates': 3, 'intelligence': 6, 'leadership': 2, 'logistics': 4, 'water magic': 4, 'air magic': 4, 'earth magic': 3, 'fire magic': 2, 'mysticism': 4, 'wisdom': 7, 'navigation': 5, 'offense': 4, 'learning': 4, 'first aid': 10, 'pathfinding': 2, 'interference': 0, 'scouting': 3, 'resistance': 2, 'archery': 3, 'tactics': 2, 'luck': 5, 'necromancy': 0},
    'ranger': {'artillery': 6, 'ballistics': 4, 'sorcery': 2, 'scholar': 1, 'diplomacy': 4, 'armorer': 8, 'eagle eye': 2, 'estates': 2, 'intelligence': 2, 'leadership': 6, 'logistics': 5, 'water magic': 3, 'air magic': 1, 'earth magic': 3, 'fire magic': 0, 'mysticism': 3, 'wisdom': 3, 'navigation': 3, 'offense': 5, 'learning': 4, 'first aid': 3, 'pathfinding': 7, 'interference': 9, 'scouting': 7, 'resistance': 9, 'archery': 8, 'tactics': 5, 'luck': 6, 'necromancy': 0},
    'druid': {'artillery': 1, 'ballistics': 4, 'sorcery': 6, 'scholar': 8, 'diplomacy': 4, 'armorer': 3, 'eagle eye': 7, 'estates': 3, 'intelligence': 7, 'leadership': 2, 'logistics': 5, 'water magic': 4, 'air magic': 2, 'earth magic': 4, 'fire magic': 1, 'mysticism': 6, 'wisdom': 8, 'navigation': 2, 'offense': 1, 'learning': 4, 'first aid': 7, 'pathfinding': 5, 'interference': 0, 'scouting': 2, 'resistance': 1, 'archery': 5, 'tactics': 1, 'luck': 9, 'necromancy': 0},
    'alchemist': {'artillery': 4, 'ballistics': 6, 'sorcery': 3, 'scholar': 3, 'diplomacy': 3, 'armorer': 8, 'eagle eye': 3, 'estates': 4, 'intelligence': 4, 'leadership': 3, 'logistics': 6, 'water magic': 2, 'air magic': 4, 'earth magic': 3, 'fire magic': 1, 'mysticism': 4, 'wisdom': 6, 'navigation': 3, 'offense': 6, 'learning': 10, 'first aid': 2, 'pathfinding': 4, 'interference': 5, 'scouting': 4, 'resistance': 5, 'archery': 5, 'tactics': 4, 'luck': 2, 'necromancy': 0},
    'wizard': {'artillery': 1, 'ballistics': 4, 'sorcery': 8, 'scholar': 9, 'diplomacy': 4, 'armorer': 1, 'eagle eye': 8, 'estates': 5, 'intelligence': 10, 'leadership': 4, 'logistics': 2, 'water magic': 3, 'air magic': 6, 'earth magic': 3, 'fire magic': 2, 'mysticism': 8, 'wisdom': 10, 'navigation': 1, 'offense': 1, 'learning': 4, 'first aid': 7, 'pathfinding': 2, 'interference': 0, 'scouting': 2, 'resistance': 0, 'archery': 2, 'tactics': 1, 'luck': 4, 'necromancy': 0},
    'demoniac': {'artillery': 5, 'ballistics': 7, 'sorcery': 3, 'scholar': 2, 'diplomacy': 4, 'armorer': 7, 'eagle eye': 3, 'estates': 3, 'intelligence': 2, 'leadership': 3, 'logistics': 10, 'water magic': 1, 'air magic': 2, 'earth magic': 3, 'fire magic': 4, 'mysticism': 2, 'wisdom': 4, 'navigation': 4, 'offense': 8, 'learning': 4, 'first aid': 2, 'pathfinding': 4, 'interference': 6, 'scouting': 5, 'resistance': 6, 'archery': 6, 'tactics': 6, 'luck': 2, 'necromancy': 0},
    'heretic': {'artillery': 4, 'ballistics': 6, 'sorcery': 6, 'scholar': 5, 'diplomacy': 3, 'armorer': 4, 'eagle eye': 4, 'estates': 2, 'intelligence': 6, 'leadership': 2, 'logistics': 3, 'water magic': 2, 'air magic': 3, 'earth magic': 4, 'fire magic': 5, 'mysticism': 10, 'wisdom': 8, 'navigation': 2, 'offense': 4, 'learning': 4, 'first aid': 5, 'pathfinding': 4, 'interference': 0, 'scouting': 3, 'resistance': 3, 'archery': 4, 'tactics': 4, 'luck': 2, 'necromancy': 0},
    'death knight': {'artillery': 5, 'ballistics': 7, 'sorcery': 4, 'scholar': 2, 'diplomacy': 2, 'armorer': 5, 'eagle eye': 4, 'estates': 0, 'intelligence': 5, 'leadership': 0, 'logistics': 5, 'water magic': 3, 'air magic': 2, 'earth magic': 4, 'fire magic': 1, 'mysticism': 4, 'wisdom': 6, 'navigation': 8, 'offense': 7, 'learning': 4, 'first aid': 0, 'pathfinding': 4, 'interference': 5, 'scouting': 4, 'resistance': 5, 'archery': 5, 'tactics': 5, 'luck': 1, 'necromancy': 10},
    'necromancer': {'artillery': 3, 'ballistics': 5, 'sorcery': 6, 'scholar': 6, 'diplomacy': 4, 'armorer': 2, 'eagle eye': 7, 'estates': 3, 'intelligence': 6, 'leadership': 0, 'logistics': 4, 'water magic': 3, 'air magic': 3, 'earth magic': 8, 'fire magic': 2, 'mysticism': 6, 'wisdom': 8, 'navigation': 5, 'offense': 3, 'learning': 4, 'first aid': 0, 'pathfinding': 6, 'interference': 0, 'scouting': 2, 'resistance': 1, 'archery': 2, 'tactics': 2, 'luck': 1, 'necromancy': 10},
    'overlord': {'artillery': 8, 'ballistics': 7, 'sorcery': 2, 'scholar': 1, 'diplomacy': 3, 'armorer': 6, 'eagle eye': 2, 'estates': 4, 'intelligence': 1, 'leadership': 8, 'logistics': 8, 'water magic': 0, 'air magic': 1, 'earth magic': 3, 'fire magic': 2, 'mysticism': 3, 'wisdom': 3, 'navigation': 4, 'offense': 8, 'learning': 4, 'first aid': 1, 'pathfinding': 5, 'interference': 6, 'scouting': 5, 'resistance': 6, 'archery': 6, 'tactics': 10, 'luck': 1, 'necromancy': 0},
    'warlock': {'artillery': 1, 'ballistics': 6, 'sorcery': 10, 'scholar': 8, 'diplomacy': 4, 'armorer': 1, 'eagle eye': 8, 'estates': 5, 'intelligence': 8, 'leadership': 3, 'logistics': 2, 'water magic': 2, 'air magic': 2, 'earth magic': 5, 'fire magic': 5, 'mysticism': 8, 'wisdom': 10, 'navigation': 4, 'offense': 1, 'learning': 4, 'first aid': 6, 'pathfinding': 2, 'interference': 0, 'scouting': 2, 'resistance': 0, 'archery': 2, 'tactics': 1, 'luck': 2, 'necromancy': 0},
    'barbarian': {'artillery': 8, 'ballistics': 8, 'sorcery': 1, 'scholar': 1, 'diplomacy': 1, 'armorer': 6, 'eagle eye': 2, 'estates': 2, 'intelligence': 1, 'leadership': 5, 'logistics': 7, 'water magic': 0, 'air magic': 3, 'earth magic': 3, 'fire magic': 2, 'mysticism': 3, 'wisdom': 2, 'navigation': 2, 'offense': 10, 'learning': 4, 'first aid': 1, 'pathfinding': 8, 'interference': 6, 'scouting': 8, 'resistance': 6, 'archery': 7, 'tactics': 8, 'luck': 3, 'necromancy': 0},
    'battle mage': {'artillery': 4, 'ballistics': 6, 'sorcery': 6, 'scholar': 4, 'diplomacy': 3, 'armorer': 4, 'eagle eye': 5, 'estates': 1, 'intelligence': 5, 'leadership': 4, 'logistics': 9, 'water magic': 3, 'air magic': 3, 'earth magic': 3, 'fire magic': 3, 'mysticism': 4, 'wisdom': 6, 'navigation': 0, 'offense': 8, 'learning': 4, 'first aid': 4, 'pathfinding': 4, 'interference': 1, 'scouting': 4, 'resistance': 4, 'archery': 4, 'tactics': 5, 'luck': 2, 'necromancy': 0},
    'beastmaster': {'artillery': 8, 'ballistics': 7, 'sorcery': 1, 'scholar': 1, 'diplomacy': 1, 'armorer': 10, 'eagle eye': 1, 'estates': 1, 'intelligence': 1, 'leadership': 5, 'logistics': 8, 'water magic': 2, 'air magic': 1, 'earth magic': 3, 'fire magic': 0, 'mysticism': 2, 'wisdom': 2, 'navigation': 8, 'offense': 5, 'learning': 4, 'first aid': 6, 'pathfinding': 8, 'interference': 5, 'scouting': 7, 'resistance': 5, 'archery': 7, 'tactics': 6, 'luck': 2, 'necromancy': 0},
    'witch': {'artillery': 1, 'ballistics': 8, 'sorcery': 8, 'scholar': 7, 'diplomacy': 2, 'armorer': 4, 'eagle eye': 10, 'estates': 1, 'intelligence': 7, 'leadership': 1, 'logistics': 3, 'water magic': 3, 'air magic': 3, 'earth magic': 3, 'fire magic': 3, 'mysticism': 8, 'wisdom': 8, 'navigation': 6, 'offense': 2, 'learning': 4, 'first aid': 8, 'pathfinding': 2, 'interference': 0, 'scouting': 2, 'resistance': 0, 'archery': 3, 'tactics': 1, 'luck': 4, 'necromancy': 0},
    'planeswalker': {'artillery': 8, 'ballistics': 8, 'sorcery': 1, 'scholar': 1, 'diplomacy': 2, 'armorer': 5, 'eagle eye': 2, 'estates': 3, 'intelligence': 1, 'leadership': 3, 'logistics': 8, 'water magic': 2, 'air magic': 2, 'earth magic': 3, 'fire magic': 3, 'mysticism': 3, 'wisdom': 2, 'navigation': 5, 'offense': 9, 'learning': 8, 'first aid': 1, 'pathfinding': 6, 'interference': 2, 'scouting': 6, 'resistance': 2, 'archery': 8, 'tactics': 8, 'luck': 2, 'necromancy': 0},
    'elementalist': {'artillery': 1, 'ballistics': 4, 'sorcery': 8, 'scholar': 8, 'diplomacy': 4, 'armorer': 1, 'eagle eye': 8, 'estates': 3, 'intelligence': 8, 'leadership': 3, 'logistics': 2, 'water magic': 6, 'air magic': 6, 'earth magic': 6, 'fire magic': 6, 'mysticism': 8, 'wisdom': 8, 'navigation': 4, 'offense': 1, 'learning': 4, 'first aid': 4, 'pathfinding': 2, 'interference': 0, 'scouting': 2, 'resistance': 0, 'archery': 2, 'tactics': 1, 'luck': 2, 'necromancy': 0},
    'captain': {'artillery': 5, 'ballistics': 5, 'sorcery': 2, 'scholar': 1, 'diplomacy': 5, 'armorer': 2, 'eagle eye': 4, 'estates': 4, 'intelligence': 3, 'leadership': 6, 'logistics': 6, 'water magic': 2, 'air magic': 3, 'earth magic': 4, 'fire magic': 2, 'mysticism': 1, 'wisdom': 1, 'navigation': 6, 'offense': 9, 'learning': 2, 'first aid': 2, 'pathfinding': 8, 'interference': 3, 'scouting': 4, 'resistance': 3, 'archery': 9, 'tactics': 6, 'luck': 7, 'necromancy': 0},
    'navigator': {'artillery': 1, 'ballistics': 2, 'sorcery': 6, 'scholar': 5, 'diplomacy': 2, 'armorer': 1, 'eagle eye': 2, 'estates': 2, 'intelligence': 8, 'leadership': 2, 'logistics': 6, 'water magic': 9, 'air magic': 6, 'earth magic': 5, 'fire magic': 2, 'mysticism': 3, 'wisdom': 8, 'navigation': 2, 'offense': 4, 'learning': 4, 'first aid': 4, 'pathfinding': 6, 'interference': 1, 'scouting': 3, 'resistance': 5, 'archery': 6, 'tactics': 4, 'luck': 4, 'necromancy': 0}
}

start_pri = {'knight': (2, 2, 1, 1),
    'cleric': (1, 0, 2, 2),
    'ranger': (1, 3, 1, 1),
    'druid': (0, 2, 1, 2),
    'alchemist': (1, 1, 2, 2),
    'wizard': (0, 0, 2, 3),
    'demoniac': (2, 2, 1, 1),
    'heretic': (1, 1, 2, 1),
    'death knight': (1, 2, 2, 1),
    'necromancer': (1, 0, 2, 2),
    'overlord': (2, 2, 1, 1),
    'warlock': (0, 0, 3, 2),
    'barbarian': (4, 0, 1, 1),
    'battle mage': (2, 1, 1, 1),
    'beastmaster': (0, 4, 1, 1),
    'witch': (0, 1, 2, 2),
    'planeswalker': (3, 1, 1, 1),
    'elementalist': (0, 0, 3, 3),
    'captain': (3, 0, 2, 1),
    'navigator': (2, 0, 1, 2)}